### PR TITLE
Makes the privacy and terms links work in footer

### PR DESCRIPTION
**Pull request by SandroLinux**
Makes the privacy and terms links work in footer because the current links redirect to the homepage

### CODE REVIEW

**Comment by EnderDev** [comment]
This will fail with other languages.

**Comment by SandroLinux** [comment]
Oh yes it would

**Comment by SandroLinux** [comment]
maybe not the best solution

**Comment by SandroLinux** [comment]
Although it would be a good temporary measure

**Comment by EnderDev** [comment]
Can there be a more elegant solution?

**Comment by SandroLinux** [comment]
> Can there be a more elegant solution?

Yes I will start working on that

**Pull request closed without merging**
